### ISSUE TITLE
Could you support images?

### ISSUE THREAD

**Issue by ivysrono** [def00111/always-preview#1]
for example, png jpg gif and so on.

**Comment by def00111** [comment]
There are already add-ons that does this:
https://addons.mozilla.org/firefox/addon/display-inline/
https://addons.mozilla.org/firefox/addon/view-content-instead-of-saving/
https://addons.mozilla.org/firefox/addon/content-type-fixer/
https://addons.mozilla.org/firefox/addon/bypass-forced-download/

**Comment by ivysrono** [comment]
Thank you very much.

**Comment by def00111** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=773942

**Comment by def00111** [comment]
Maybe this will also be possible for images etc.
